repos:
  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v1.0.2 # Get the latest from: https://github.com/tofuutils/pre-commit-opentofu/releases
    hooks:
      - id: tofu_fmt
      - id: tofu_validate
      - id: tofu_tflint
      - id: tofu_docs
  - repo: https://github.com/mineiros-io/pre-commit-hooks
    rev: v0.5.1 # Check for the latest version: https://github.com/mineiros-io/pre-commit-hooks/releases
    hooks:
      - id: terramate-generate
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.17.0
    hooks:
      - id: terraform-docs-go
        name: terraform-docs
        args: ["-c", ".terraform-docs.yml", "./modules"]
        pass_filenames: false
