formatter: "markdown table" # this is required

header-from: main.tf
footer-from: ""

recursive:
  enabled: true
  path: .

sections:
  hide: []
  show: []

  hide-all: false # deprecated in v0.13.0, removed in v0.15.0
  show-all: true  # deprecated in v0.13.0, removed in v0.15.0

content: "{{ .Header }}\n{{ .Footer }}\n{{ .Inputs }}\n{{ .Modules }}\n{{ .Outputs }}\n{{ .Providers }}\n{{ .Requirements }}\n{{ .Resources }}"

output:
  file: "README.md"
  mode: inject
   

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true